apiVersion: v1
kind: Service
metadata:
  name: health-monitoring
  namespace: example-applications
spec:
  selector:
    app: health-monitoring
  ports:
    - port: 80
      targetPort: 4011
      nodePort: 30123
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-monitoring
  namespace: example-applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-monitoring
  template:
    metadata:
      labels:
        app: health-monitoring
    spec:
      containers:
        - name: health-monitoring
          image: ramya2812/heartrate_monitoring
          ports:
            - containerPort: 4011
          env:
            - name: MONGO_URL
              value: mongodb://mongo-heart:27017/Healthcheck
          imagePullPolicy: Always
