apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-heart
  namespace: example-applications
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/ramya/data-mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-heart
  namespace: example-applications
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-heart
  namespace: example-applications
spec:
  selector:
    app: mongo-heart
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-heart
  namespace: example-applications
spec:
  selector:
    matchLabels:
      app: mongo-heart
  template:
    metadata:
      labels:
        app: mongo-heart
    spec:
      containers:
        - name: mongo-heart
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc-heart

