apiVersion: v1
kind: Service
metadata:
  name: server-low
  namespace: example-applications
spec:
  selector:
    app: server-low
  ports:
    - port: 81
      targetPort: 4001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-low
  namespace: example-applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-low
  template:
    metadata:
      labels:
        app: server-low
    spec:
      containers:
        - name: server-low
          image: ramya2812/server-low
          ports:
            - containerPort: 4001
          imagePullPolicy: Always
