apiVersion: v1
kind: Service
metadata:
  name: server-scale
  namespace: example-applications
spec:
  selector:
    app: server-scale
  ports:
    - port: 81
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-scale
  namespace: example-applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-scale
  template:
    metadata:
      labels:
        app: server-scale
    spec:
      containers:
        - name: server-scale
          image: ramya2812/server-scale
          ports:
            - containerPort: 4000
          imagePullPolicy: Always
